# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    groups:
      gomod:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
