version: 2
builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - id: foo
    name_template: >-
      gke-auth_
      {{- .Version }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}_
      {{- if eq .Os "linux"}}Linux
      {{- else }}{{ .Os }}{{ end }}
checksum:
  name_template: 'checksums.txt'
