version: 2
builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - name_template: gke-auth_{{ .Version }}_{{ if eq .Os "linux"}}Linux{{ else }}{{ .Os }}{{ end }}_{{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
