name: Test Action

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['v0.1.0', 'latest-release', 'tip']
      fail-fast: false
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: './go.mod'
      - uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f # v4.0.0

      - uses: 'google-github-actions/auth@v2.1.4'
        with:
          workload_identity_provider: 'projects/30098225237/locations/global/workloadIdentityPools/gha-pool/providers/gha-provider'
          service_account: 'gha-sa@imjasonh-autopilot.iam.gserviceaccount.com'

      - uses: imjasonh/gke-auth@main
        with:
          version: ${{ matrix.version }}
          project:  imjasonh-autopilot
          location: us-east1
          cluster:  autopilot

      - run: kubectl get pods
