name: gcloud

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  gcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: azure/setup-kubectl@829323503d1be3d00ca8346e5391ca0b07a9ab0d # v5.1.0

      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: 'projects/535085602168/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: 'gke-auth@imjasonh.iam.gserviceaccount.com'

      - uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1
        with:
          project_id: imjasonh
          install_components: gke-gcloud-auth-plugin
      - run: |
          gcloud container clusters get-credentials autopilot \
              --region us-east4

      - run: kubectl get pods

      - run: gcloud auth configure-docker us-east4-docker.pkg.dev
      - uses: imjasonh/setup-crane@main
      - run: crane catalog us-east4-docker.pkg.dev
